apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mysql
  namespace: wordpress-example
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        name: mysql
        version: latest
    spec:
      containers:
      - image: mariadb:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: aStr0ngPassW0rd
        - name: MYSQL_DATABASE
          value: wordpress
        volumeMounts:
        - name: db-folder
          mountPath: /var/lib/mysql
      volumes:
        - name: db-folder
          emptyDir: {}
