apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wordpress-example
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql

