apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-example
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer 
