#!/bin/bash

export BINDIR=/usr/local/bin

export BITSDIR=/data/BITS

# CLI Tools version
export BOSHRELEASE=5.3.1
export HELMRELEASE=2.11.0
export OMRELEASE=0.41.0

#Pivotal network 
export PIVNETRELEASE=0.0.54
export APIREFRESHTOKEN="your-token"

# Pivotal SW Releases
export OPSMANRELEASE=2.3.194
export PKSRELEASE=1.2.2
export HARBORRELEASE=1.6
export STEMCELLRELEASE=97.17

# VMware Download Account
export VMWUSER='user@acme.fr'
export VMWPASS='Password123'

# VMware SW Releases
export OVFTOOLPG=OVFTOOL430
export NSXTPG=NSX-T-230
