apiVersion: v1
kind: Pod
metadata:
  name: test-vmdk
  labels:
    app: test-vmdk 
spec:
  containers:
  - image: nginx 
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    # This VMDK volume must already exist.
    vsphereVolume:
      volumePath: "[Datastore] myvol.vmdk"
      fsType: ext4

---
apiVersion: v1
kind: Service
metadata:
  name: svc-test-vmdk 
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: test-vmdk 
  type: LoadBalancer
