kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: zeroedthick
    diskStripes: "3"
    hostFailuresToTolerate: "1"
    cachereservation: "20"
