# on ESX: vmkfstools -c 2G /vmfs/volumes/Datastore/myvol.vmdk 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[Datastore] myvol"
    fsType: ext4
