kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-001
  annotations:
    volume.beta.kubernetes.io/storage-class: thin-disk 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
