apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: ${NAMESPACE} 
type: Opaque
data:
  password: ${PASSWORD} 

---

apiVersion: v1
kind: Pod
metadata:
  name: mariadb 
  namespace: ${NAMESPACE} 
  labels:
    app: mariadb 
spec:
  containers:
  - name: mariadb
    image: mariadb/server:10.1.37
    resources:
      limits:
        cpu: 10m
        memory: 100Mi
      requests:
        cpu: 8m
        memory: 90Mi
    env:
      - name: MARIADB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret 
            key: password 
    volumeMounts:
    - mountPath: /var/lib/mysql 
      name: data 
    ports:
        - containerPort: 3306
  volumes:
  - name: data 
    # This VMDK volume must already exist.
    vsphereVolume:
      volumePath: "[${DATASTORE}] ${VMDK}"
      fsType: ext4

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service-lb
  namespace: ${NAMESPACE} 
spec:
  type: LoadBalancer 
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
